# Generated by Django 4.0.4 on 2022-05-29 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('dollar_cost', models.FloatField()),
                ('delivery_date', models.DateField()),
                ('ruble_cost', models.FloatField()),
            ],
        ),
    ]
